name: Webserv action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verify C++ version
      run: c++ --version

    - name: Create build directories
      run: |
        mkdir -p obj
        mkdir -p src
        mkdir -p inc

    - name: Build project
      run: make

    - name: Check executable exists
      run: |
        if [ ! -f webserve ]; then
          echo "Executable not created"
          exit 1
        fi

    - name: Test compilation flags
      run: |
        if ! make | grep -q "c++ -Wall -Wextra -Werror -std=c++98"; then
          echo "Required compilation flags not used"
          exit 1
        fi

    - name: Clean build
      run: |
        make fclean
        if [ -f webserve ] || [ -d obj ]; then
          echo "Clean failed"
          exit 1
        fi

    - name: Rebuild
      run: make re
